pipeline:
  connect:
    image: appleboy/drone-ssh
    username: root
    host: ${DEPLOY_HOST}
    password: ${DEPLOY_PASSWORD}
    script:
      - echo hello
  build:
    image: node:alpine
    commands:
      - npm install
      - npm run lint
      - npm test
  slack:
    image: plugins/slack
    channel: drone
    username: drone
    secrets: [slack_webhook]
  publish:
    image: plugins/docker
    username: ecwyne
    email: ecwyne@gmail.com
    repo: ecwyne/servicebus-test
    tags: latest
    secrets: [docker_password]
  deploy:
    image: appleboy/drone-ssh
    username: root
    secrets: [deploy_host, deploy_password]
    script:
      - docker pull ecwyne/servicebus-test:latest
      - docker service update --image ecwyne/servicebus-test:latest servicebus-test