pipeline:
  build:
    image: node:alpine
    commands:
      - npm install
      - npm test
  slack:
    image: plugins/slack
    channel: drone
    username: drone
    secrets: [slack_webhook]
  dockerhub:
    image: plugins/docker
    username: ecwyne
    email: ecwyne@gmail.com
    repo: ecwyne/servicebus-test
    tags: latest
    registry: hub.docker.com
    secrets: [dockerhub_password]